name: Check
on:
  push:
    branches:
      - "**"

jobs:
  fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cookielab/container-image-terraform:1.12
      options: --user root
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Check Terraform format
        run: terraform fmt -check=true
  lint:
    name: TF Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cookielab/container-image-terraform:1.12
      options: --user root
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Check TF lint
        run: tflint
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cookielab/container-image-terraform:1.12
      options: --user root
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Inject additional provider
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "test_injection.tf"
          FILE_DATA: |
            provider "aws" {
              alias = "us_east_1"
            }
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
